"""add candles table for charts

Revision ID: a2a978e4838a
Revises: 9e51272869cb
Create Date: 2025-09-01 14:13:55.910435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2a978e4838a'
down_revision: Union[str, Sequence[str], None] = '9e51272869cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'open_time', name='uq_candle_symbol_interval_open')
    )
    op.create_index(op.f('ix_candles_interval'), 'candles', ['interval'], unique=False)
    op.create_index(op.f('ix_candles_open_time'), 'candles', ['open_time'], unique=False)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.drop_table('candle_5m')
    op.drop_table('candle_1m')
    op.alter_column('candles_1m', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('candles_1m', 'open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('candles_1m', 'high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('candles_1m', 'low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('candles_1m', 'close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.drop_constraint(op.f('candles_1m_symbol_bucket_start_key'), 'candles_1m', type_='unique')
    op.create_index('ix_c1m_bucket_start', 'candles_1m', ['bucket_start'], unique=False)
    op.create_index(op.f('ix_candles_1m_bucket_start'), 'candles_1m', ['bucket_start'], unique=False)
    op.create_index(op.f('ix_candles_1m_id'), 'candles_1m', ['id'], unique=False)
    op.create_index(op.f('ix_candles_1m_symbol'), 'candles_1m', ['symbol'], unique=False)
    op.create_unique_constraint('uq_c1m_symbol_bucket', 'candles_1m', ['symbol', 'bucket_start'])
    op.alter_column('candles_5m', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('candles_5m', 'open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('candles_5m', 'high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('candles_5m', 'low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('candles_5m', 'close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.drop_constraint(op.f('candles_5m_symbol_bucket_start_key'), 'candles_5m', type_='unique')
    op.create_index('ix_c5m_bucket_start', 'candles_5m', ['bucket_start'], unique=False)
    op.create_index(op.f('ix_candles_5m_bucket_start'), 'candles_5m', ['bucket_start'], unique=False)
    op.create_index(op.f('ix_candles_5m_id'), 'candles_5m', ['id'], unique=False)
    op.create_index(op.f('ix_candles_5m_symbol'), 'candles_5m', ['symbol'], unique=False)
    op.create_unique_constraint('uq_c5m_symbol_bucket', 'candles_5m', ['symbol', 'bucket_start'])
    op.alter_column('ticks', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ticks', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.drop_constraint(op.f('ticks_symbol_ts_key'), 'ticks', type_='unique')
    op.create_index(op.f('ix_ticks_id'), 'ticks', ['id'], unique=False)
    op.create_index(op.f('ix_ticks_symbol'), 'ticks', ['symbol'], unique=False)
    op.create_index(op.f('ix_ticks_ts'), 'ticks', ['ts'], unique=False)
    op.create_unique_constraint('uq_ticks_symbol_ts', 'ticks', ['symbol', 'ts'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ticks_symbol_ts', 'ticks', type_='unique')
    op.drop_index(op.f('ix_ticks_ts'), table_name='ticks')
    op.drop_index(op.f('ix_ticks_symbol'), table_name='ticks')
    op.drop_index(op.f('ix_ticks_id'), table_name='ticks')
    op.create_unique_constraint(op.f('ticks_symbol_ts_key'), 'ticks', ['symbol', 'ts'], postgresql_nulls_not_distinct=False)
    op.alter_column('ticks', 'price',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('ticks', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('uq_c5m_symbol_bucket', 'candles_5m', type_='unique')
    op.drop_index(op.f('ix_candles_5m_symbol'), table_name='candles_5m')
    op.drop_index(op.f('ix_candles_5m_id'), table_name='candles_5m')
    op.drop_index(op.f('ix_candles_5m_bucket_start'), table_name='candles_5m')
    op.drop_index('ix_c5m_bucket_start', table_name='candles_5m')
    op.create_unique_constraint(op.f('candles_5m_symbol_bucket_start_key'), 'candles_5m', ['symbol', 'bucket_start'], postgresql_nulls_not_distinct=False)
    op.alter_column('candles_5m', 'close',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('candles_5m', 'low',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('candles_5m', 'high',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('candles_5m', 'open',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('candles_5m', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('uq_c1m_symbol_bucket', 'candles_1m', type_='unique')
    op.drop_index(op.f('ix_candles_1m_symbol'), table_name='candles_1m')
    op.drop_index(op.f('ix_candles_1m_id'), table_name='candles_1m')
    op.drop_index(op.f('ix_candles_1m_bucket_start'), table_name='candles_1m')
    op.drop_index('ix_c1m_bucket_start', table_name='candles_1m')
    op.create_unique_constraint(op.f('candles_1m_symbol_bucket_start_key'), 'candles_1m', ['symbol', 'bucket_start'], postgresql_nulls_not_distinct=False)
    op.alter_column('candles_1m', 'close',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('candles_1m', 'low',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('candles_1m', 'high',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('candles_1m', 'open',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('candles_1m', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('candle_1m',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('candle_1m_pkey')),
    sa.UniqueConstraint('symbol', 'ts', name=op.f('candle_1m_symbol_ts_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('candle_5m',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('candle_5m_pkey')),
    sa.UniqueConstraint('symbol', 'ts', name=op.f('candle_5m_symbol_ts_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_index(op.f('ix_candles_open_time'), table_name='candles')
    op.drop_index(op.f('ix_candles_interval'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
